spring.application.name=concert-tracker
spring.datasource.url=jdbc:mysql://localhost:3306/concert_tracker
spring.datasource.username=root
spring.datasource.password=Sb110464@
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
